# Generated by Django 3.2 on 2023-12-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_descripcion_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripcion_articulo',
            new_name='texto',
        ),
    ]
